#!/bin/bash
#the script

#sys info
username=$(whoami) 
date_time=$(date) 
hstname=$(hostname) 
opsys=$(lsb_release -a |grep "Description"| awk '{print $2 $3 $4}') 
up_time=$(uptime | awk '{print $3 $4}') 
cur_cpu_speed=$(sudo dmesg | grep 'vmware: TSC'|awk '{print $10 $11}')
max_cpu_speed=$(cat /proc/cpuinfo |grep 'model name'|head -1|awk '{print $10}')

#hardware info
cpuMake=$(lscpu | grep 'Model name'| awk '{print $3 $4 $5 $6 $7}')

# breaking down ram size
ram_space=$(free -h |grep Mem|awk '{print $2}')
#place disk_info in double quotes for the output
disk_info=$(lsblk -o NAME,MODEL,SIZE |grep sd |awk '{print $1, $2, $3, $4, $5}')

video_info=$(lspci | grep -i vga | awk -F 'controller: ' '{print $2}')
System Report generated by USERNAME, DATE/TIME

#network info
FQDName=$(hostname --fqdn)
hostaddr=$(hostname -I)
d_gateway=$(ip route | grep default |awk '{print $3}')
dns_server=$(cat /etc/resolv.conf |grep nameserver |awk '{print $2}')
network_model=$(sudo lshw -C network | grep product |head -1| awk -F 'product: ' '{print $2}')
network_make=$(sudo lshw -C network | grep vendor |head -1| awk -F 'vendor: ' '{print $2}')
ipCIDR=$(ip addr |grep -v ' lo'|grep -w "inet"|awk '{print $2}')

#System Status
logged_users=$(who|awk '{print$1}')
disk_space=$(df -h|awk '{print $1,$4}')
process_count=$(ps -e |wc -l)
load_avg=$(uptime|awk '{print $9,$10,$11}')
mem_alocate=$(free -h)
listen_ports=$(sudo ss -tuln|grep LISTEN|awk -F ':' '{print $1, $2 }'|awk '{print $6}')
uwf_rules=$(sudo ufw status)


cat <<E0F
System Report generated by $USERNAME, $DATE_TIME

System Information
-------------------
Hostname: $hstname
OS: $opsys
Uptime: $up_time

Hardware Information
----------------------
cpu: $cpuMake
Speed: $cur_cpu_speed $max_cpu_speed
Ram: $ram_space
Disk(s): $disk_info
Video: $video_info

Network Information
---------------------
FQDN: $FQDName
Host Address: $hostaddr
Gateway IP: $d_gateway
DNS Server: $dns_server

InterfaceName: $network_make $network_model
IP Address: $ipCIDR

System Status
--------------
Users Logged In: $logged_users
Disk Space: $disk_space
Process Count: $process_count
Load Averages: $load_avg
Memory Allocation: $mem_alocate
Listening Network Ports: $listen_ports
UFW Rules: "$uwf_rules"
E0F

